apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce 
  volumeName: task-pv-volume
  resources:
    requests:
      storage: 1Gi