---
 - name:  provisioning EC2 instances using Ansible
   hosts: localhost
   connection: local
   gather_facts: False
   tags: provisioning

   vars:
     keypair: 06Dec
     instance_type: t2.micro
     image: ami-0907c2c44ea451f84
     wait: yes
     group: k8cluster
     count: 2
     region: ap-southeast-1
     zones: ap-southeast-1b
     security_group: k8cluster-security-group
   
   tasks:

     - name: Create security group
       local_action: 
         module: ec2_group
         name: "{{ security_group }}"
         description: Security Group for webserver Servers
         region: "{{ region }}"
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
         rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
       register: basic_firewall
     - name: Launch the new EC2 Instance
       local_action:  ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
       register: ec2
     - name: Add Tagging to EC2 instance
       local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
       with_items: "{{ ec2.instances }}"
       args:
         tags:
           Name: k8cluster

     - name: associate new elastic IPs with each of the instances
       ec2_eip:
        device_id: "{{ item }}"
	region: "{{ region }}"
       with_items: "{{ ec2.instance_ids }}"

     - name: setup a simple load balancer
       ec2_elb_lb:
        name: myelb
        state: present
        region: "{{ region }}"
        zones:
          - "{{ zones }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
       register: myelb

     - name: add the webservers to the load balancer
       local_action: ec2_elb
       args:
        instance_id: "{{ item }}"
        ec2_elbs: myelb
        state: present
        region: "{{ region }}"
       with_items: "{{ ec2.instance_ids }}"